spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:esiqueira}:${DB_PASSWORD:Siqueira_123}@webfluxconceptcluster.9rpxke6.mongodb.net/${DB_NAME:webflux-concept}?retryWrites=true&w=majority&appName=WebfluxConceptCluster
      auto-index-creation: true
  application:
    name: webflux-concept
